#! /usr/bin/env python
import sys
import os
import hashlib

def get_files(path):
    files = []
    for result in os.walk(path):
        for filename in result[2]:
            fullfile = os.path.join(result[0], filename)
            files.append(fullfile)
    return files

def hash_files(files_list):
    hash_list =[]
    for file_path in files_list:
        hash_list.append((
            file_path,
            hashlib.sha256(open(file_path, 'rb').read()).hexdigest()
        ))
    return hash_list


def main(args):
    dir_1, dir_2 = args[1:]
    dir_1_hashes = hash_files(get_files(dir_1))
    dir_2_hashes = hash_files(get_files(dir_2))

    
    # print(dir_1_files, dir_2_files)
    'Failed. Expected: 1 difference between directories: test3.a contains c.txt that cannot be found in test3.b'


if __name__ == '__main__':
    main(sys.argv)
